using System;
using System.Runtime.InteropServices;
using System.Collections.Generic;
using System.Collections;

namespace Gtk
{    
    public abstract class SignalArgs : EventArgs
    {
        // Constructor populates the signal data
        // This is typically generated by gir data
        internal abstract void Populate(Value[] values);
    }

    public delegate void SignalHandler<T>(object sender, T args);
}