using System;
using System.Runtime.InteropServices;
using System.Collections.Generic;
using System.Collections;

namespace Gtk
{    
    public class SignalArgs : EventArgs
    {
        // Constructor populates the signal data
        // This is typically generated by gir data
        internal virtual void Populate(Value[] values) {}
    }

    public delegate void SignalHandler<T>(object sender, T args);
}